#custom_venv_dir: /opt/awx/venv
- name: Create VenV root {{ custom_venv_dir }} directory
  ansible.builtin.file:
    path: "{{ custom_venv_dir }}"
    state: directory
    mode: "0775"
    recurse: true
    owner: root
    group: docker
  become: true
  when: custom_venv_dir is defined and (custom_venvs is defined and custom_venvs|length>0)

- name: Delete custom VenV directories (clean install)
  ansible.builtin.file:
    path: "{{ custom_venv_dir }}/{{ item.name }}"
    state: absent
  loop: "{{ custom_venvs }}"
  become: true
  when: custom_venv_delete_before_install is defined and (custom_venv_delete_before_install|bool)

- name: Install specific Python version
  ansible.builtin.include_tasks: specific_python.yml
  vars:
    python_version: "{{ item.python_version }}"
  loop: "{{ custom_venvs }}"
  when: item.python_version is defined

- name: Install default packages lastes version in custom VenV
  ansible.builtin.pip:
    name: "{{ custom_venv_default_pip_packages | list }}"
    virtualenv: "{{ custom_venv_dir }}/{{ item.name }}"
    state: latest
    virtualenv_site_packages: "{{ item.install_site_packages |default('no') }}"
    #virtualenv_python: "{{ omit if item.python_version is not defined or (custom_python_dir + '/Python-'+ item.python_version + '/python3') }}"
    virtualenv_python: "{% if item.python_version is defined %}{{ custom_python_dir }}/Python-{{ item.python_version  }}/bin/python3{% else %}/usr/local/bin/python3{% endif %}"
    umask: "0022"
  become: false
  loop: "{{ custom_venvs }}"

- name: Install Ansible packages in custom Python VenV
  ansible.builtin.pip:
    name: "{{ item.ansible_pip_packages | list }}"
    virtualenv: "{{ custom_venv_dir }}/{{ item.name }}"
    virtualenv_site_packages: "{{ item.install_site_packages |default('no') }}"
    #virtualenv_python: "{{ omit if item.python_version is not defined or (custom_python_dir + '/Python-'+ item.python_version + '/python3') }}"
    virtualenv_python: "{% if item.python_version is defined %}{{ custom_python_dir }}/Python-{{ item.python_version  }}/bin/python3{% else %}/usr/local/bin/python3{% endif %}"
    # virtualenv_python: '/opt/python/Python-3.9.8/bin/python3'
    umask: "0022"
  become: false
  loop: "{{ custom_venvs }}"
