---
## Requirements: Docker and Docker-compose ! install on forehand or use additional roles

- name: check if version is correct for Docker installation
  ansible.builtin.assert:
    that:
      - awx_version is version_compare('17.1.0', '<=', strict=true)
    fail_msg: "Only AWX version 17.1.0 are possible with this role"


# - name: Clean GIT repo
#   ansible.builtin.file:
#     path: "{{ awx_repo_dir }}"
#     state: absent


- name: Clone AWX into configured directory
  ansible.builtin.git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    update: "{{ awx_keep_updated }}"
    force: true
    accept_hostkey: true
  changed_when: false
  become: "{{ awx__install_as_root }}"

- name: Change variables in installation inventory of AWX
  ansible.builtin.replace:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { dest: "{{ awx_repo_dir }}/installer/inventory", regexp: "^postgres_data_dir=.*$", replace: "postgres_data_dir={{ awx__postgres_data_dir }}" }
    - { dest: "{{ awx_repo_dir }}/installer/inventory", regexp: "^host_port=.*$", replace: "host_port={{ awx__port_web_http }}" }
    - { dest: "{{ awx_repo_dir }}/installer/inventory", regexp: "^host_port_ssl=.*$", replace: "host_port_ssl={{ awx__port_web_https }}" }
    - { dest: "{{ awx_repo_dir }}/installer/inventory", regexp: "^docker_compose_dir=.*$", replace: "docker_compose_dir={{ docker_compose_dir }}" }
    - { dest: "{{ awx_repo_dir }}/installer/inventory", regexp: "^#project_data_dir=.*$", replace: "project_data_dir={{ awx__project_data_dir }}" }
    - { dest: "{{ awx_repo_dir }}/installer/inventory", regexp: "^#alternate_dns_servers=.*$", replace: "alternate_dns_servers={{ awx__dns_servers }}" }
    - { dest: "{{ awx_repo_dir }}/installer/inventory", regexp: "^#admin_user=.*$", replace: "admin_user={{ awx__admin_user }}" }
    - { dest: "{{ awx_repo_dir }}/installer/inventory", regexp: "^# admin_password=.*$", replace: "admin_password={{ awx__admin_password }}" }
  changed_when: false
  no_log: true
  become: "{{ awx__install_as_root }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: root # AWX Runs as user/group root
    group: docker
    recurse: true
  become: true
  with_items:
    - "{{ awx__postgres_data_dir }}"
    - "{{ awx__project_data_dir }}"

- name: Custom custom_venv_dir found - edit config and add docker-compose-override.yml
  block:
  # - name: Disable auto start containers in AWX playbook
  #   set_fact:
  #     compose_start_containers: false

  # Create compose dir already, otherwise first run it doesnt exist (it will be created in ansible-playbook install.yml)
  - name: Create {{ docker_compose_dir }} directory
    ansible.builtin.file:
      path: "{{ docker_compose_dir }}"
      state: directory
      mode: "0775"
      owner: root # AWX Runs as user/group root
      group: docker
      recurse: true
    become: true

  - name: Create VenV root {{ custom_venv_dir }} directory
    ansible.builtin.file:
      path: "{{ custom_venv_dir }}"
      state: directory
      mode: "0775"
      owner: root
      group: docker
      recurse: true
    become: true
    when: custom_venv_dir is defined and (custom_venvs is defined and custom_venvs|length>0)

  - name: Create VenV python dir
    ansible.builtin.file:
      path: "{{ custom_python_dir }}"
      state: directory
      mode: "0775"
      owner: root
      group: docker
      recurse: true
    become: true
    when: custom_python_dir is defined and (custom_venvs is defined and custom_venvs|length>0)

  - name: Change custom_venv_dir in inventory file
    ansible.builtin.replace:
      dest: "{{ awx_repo_dir }}/installer/inventory"
      regexp: "^#custom_venv_dir=.*$"
      replace: "custom_venv_dir={{ custom_venv_dir }}"

  - name: Copy docker-compose.override.yml template
    ansible.builtin.template:
      src: docker-compose.override.yml.j2
      dest: "{{ docker_compose_dir }}/docker-compose.override.yml"
  when: custom_venv_dir is defined

# - name: remove docker-py if exist (conflicting package)
#   ansible.builtin.pip:
#     name:
#       - docker-py
#     state: absent
#   become: "{{ awx__install_as_root }}"

- name: Run the AWX installation playbook
  command: "ansible-playbook -i inventory install.yml"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
  become: "{{ awx__install_as_root }}"
