---
- name: Include OS-specific vars
  include_vars: "{{ ansible_os_family }}_docker.yml"

- name: Install RedHet prerequistics
  include_tasks: redhat_prereq.yml
  when: "ansible_os_family == 'RedHat'"

- name: Install packages for OS
  ansible.builtin.package:
    name={{ item.name }}
    version={{ item.version | default(omit) }}
  with_items: "{{ os_packages }}"
  become: true

- name: Install default pip packages
  ansible.builtin.pip:
    name={{ item }}
    state=forcereinstall
    executable=pip3
    extra_args=--user
    umask=0022
  with_items: "{{ default_pip_packages }}"
  become: "{{ awx__install_as_root }}"

- name: Install OS specific pip packages
  ansible.builtin.pip:
    name={{ item.name }}
    version={{ item.version | default('latest') }}
    executable=pip3
    extra_args=--user
    umask=0022
  with_items: "{{ python_packages }}"
  tags:
    - pip
    - packages
  become: "{{ awx__install_as_root }}"



- name: Install Custom VenV (only for version below 18.0.0)
  include_tasks: awx_venv.yml
  when: custom_venvs is defined and custom_venvs|length>0 and (awx_version is version('18.0.0', '<'))

- name: Install AWX version 17 or below
  ansible.builtin.include_tasks: install_awx_docker_pre_v17.yml
  when: not skip_awx_install|bool and (awx_version is version('18.0.0', '<'))

- name: Install AWX above version v17
  ansible.builtin.include_tasks: install_awx_docker.yml
  when: not skip_awx_install|bool and (awx_version is version('17.1.0', '>'))

- name: Configure base sessings
  ansible.builtin.include_tasks: config_awx.yml
