
- name: Install prerequestics for RHEL
  block:
  - name: Install the latest version of Python3.9 RHEL
    ansible.builtin.dnf:
      name: python3.9
      state: latest

  - name: Set python alternatives to 3.9
    community.general.alternatives:
      link: /bin/python3
      name: python3
      path: /usr/bin/python3.9
      # state: "selected"

  - name: Install the latest version of python3-pip
    ansible.builtin.dnf:
      name: python3-pip
      state: latest

  - name: Install the latest version of python3-wheel
    ansible.builtin.dnf:
      name: python3-wheel
      state: latest

# - name: Remove Python 3.6 from RHEL
#   ansible.builtin.dnf:
#     name: python3.6
#     state: absent
#   when: "ansible_os_family == 'RedHat'"
#   become: true

  become: true
