---
- name: Converge
  hosts: all
  become: false
  vars:
    # Set bind to tmp because DiD setup (See molecule binding)
    awx__17_1_0_config_path: /tmp/awx_config
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    # - name: Debug systemctl status
    #   command: systemctl is-system-running
    #   register: sys_state
    #   ignore_errors: true

    # - debug: var=sys_state.stdout

    - name: Wait for systemd to complete initialization
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: systemctl_status.stdout in ['running', 'degraded']
      retries: 10
      delay: 2
      changed_when: false
      failed_when: systemctl_status.rc > 1
      when:
        - ansible_service_mgr == 'systemd'
        - ansible_virtualization_type != "docker"

  roles:
    # - role: bsmeding.docker
    - role: bsmeding.awx_docker
