driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    privileged: true  # If you need Docker inside Docker

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml

verifier:
  name: ansible