---
- name: Verify - AWX is running
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - "yml"

    - name: Check that AWX is running
      ansible.builtin.uri:
        url: "http://localhost:80"
        return_content: true
      register: awx_output
      failed_when: awx_output is failed or awx_output.status != 200
      # or "'Welcome to our server' not in local_webserver_output.content"

    - name: Show output
      debug:
        var: awx_output

    - name: Verify awx container is running
      community.docker.docker_container_info:
        name: "{{ awx__name }}"
      register: awx_container_info

    - name: Check awx container status
      assert:
        that:
          - awx_container_info.exists
            - awx_container_info.container.State.Status == "running"
        fail_msg: "AWX container is not running"
