name: Molecule CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: bsmeding.awx_docker

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible & Molecule (delegated built-in)
        run: |
          pip install --no-cache-dir \
            ansible-core==2.16.4 \
            molecule==24.2.1 \
            netaddr \
            requests
        working-directory: bsmeding.awx_docker

      - name: Debug Molecule drivers
        run: molecule list --debug
        working-directory: bsmeding.awx_docker

      - name: Run Molecule test
        run: molecule test
        working-directory: bsmeding.awx_docker
        env:
          MOLECULE_DRIVER_NAME: delegated
