---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 0"

# defaults:
#   run:
#     working-directory: 'bsmeding.awx_docker'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'bsmeding.awx_docker'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint
        working-directory: bsmeding.awx_docker

      - name: Lint code.
        run: |
          yamllint .
        working-directory: bsmeding.awx_docker

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian11
          - debian12
          # - rockylinux8
          # - rockylinux9
          # - ubuntu2204
          # - ubuntu2404
          # - fedora39
          # - fedora40

    steps:
      # AWX needs a lot of space, not always available at free runners
      - name: Free up disk space
        run: |
          echo "Freeing up disk space..."
          docker system prune -af
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo apt-get clean
          df -h

      - name: Aggressively clean Docker cache
        run: |
          docker system prune -af --volumes
          docker builder prune -af
          df -h
          df -i

      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'bsmeding.awx_docker'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule==24.2.1 molecule-plugins[docker]==23.5.3 docker==7.0.0 netaddr==1.2.1 requests==2.31.0
        working-directory: bsmeding.awx_docker

      - name: Run Molecule tests.
        run: molecule test
        working-directory: bsmeding.awx_docker
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
