---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 0"

defaults:
  run:
    working-directory: 'bsmeding.awx_docker'

jobs:
  test:
    name: Molecule test (Docker)
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        privileged: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --no-cache-dir \
            ansible-core==2.16.4 \
            molecule==24.2.1 \
            molecule-plugins[docker]==23.5.3 \
            docker \
            netaddr \
            requests

      - name: Run Molecule
        run: molecule test